CREATE TABLE IF NOT EXISTS city (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  active BOOLEAN NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_city_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS theatre (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  active BOOLEAN NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_theatre_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS city_theatres (
  city_id BIGINT NOT NULL,
  theatres_id BIGINT NOT NULL,
  PRIMARY KEY (city_id, theatres_id),
  FOREIGN KEY (city_id) REFERENCES city(id) ON DELETE CASCADE,
  FOREIGN KEY (theatres_id) REFERENCES theatre(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
